package com.dadoutek.uled.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dadoutek.uled.DbModel.DbSceneActions;
import com.dadoutek.uled.DbModel.DbScene;

import com.dadoutek.uled.dao.DbSceneActionsDao;
import com.dadoutek.uled.dao.DbSceneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbSceneActionsDaoConfig;
    private final DaoConfig dbSceneDaoConfig;

    private final DbSceneActionsDao dbSceneActionsDao;
    private final DbSceneDao dbSceneDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbSceneActionsDaoConfig = daoConfigMap.get(DbSceneActionsDao.class).clone();
        dbSceneActionsDaoConfig.initIdentityScope(type);

        dbSceneDaoConfig = daoConfigMap.get(DbSceneDao.class).clone();
        dbSceneDaoConfig.initIdentityScope(type);

        dbSceneActionsDao = new DbSceneActionsDao(dbSceneActionsDaoConfig, this);
        dbSceneDao = new DbSceneDao(dbSceneDaoConfig, this);

        registerDao(DbSceneActions.class, dbSceneActionsDao);
        registerDao(DbScene.class, dbSceneDao);
    }
    
    public void clear() {
        dbSceneActionsDaoConfig.clearIdentityScope();
        dbSceneDaoConfig.clearIdentityScope();
    }

    public DbSceneActionsDao getDbSceneActionsDao() {
        return dbSceneActionsDao;
    }

    public DbSceneDao getDbSceneDao() {
        return dbSceneDao;
    }

}
