package com.dadoutek.uled.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dadoutek.uled.model.DbModel.DbConnector;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_CONNECTOR".
*/
public class DbConnectorDao extends AbstractDao<DbConnector, Long> {

    public static final String TABLENAME = "DB_CONNECTOR";

    /**
     * Properties of entity DbConnector.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MeshAddr = new Property(1, int.class, "meshAddr", false, "MESH_ADDR");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Open = new Property(3, boolean.class, "open", false, "OPEN");
        public final static Property MacAddr = new Property(4, String.class, "macAddr", false, "MAC_ADDR");
        public final static Property MeshUUID = new Property(5, int.class, "meshUUID", false, "MESH_UUID");
        public final static Property ProductUUID = new Property(6, int.class, "productUUID", false, "PRODUCT_UUID");
        public final static Property BelongGroupId = new Property(7, Long.class, "belongGroupId", false, "BELONG_GROUP_ID");
        public final static Property Index = new Property(8, int.class, "index", false, "INDEX");
        public final static Property Color = new Property(9, int.class, "color", false, "COLOR");
        public final static Property Status = new Property(10, int.class, "status", false, "STATUS");
    }


    public DbConnectorDao(DaoConfig config) {
        super(config);
    }
    
    public DbConnectorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_CONNECTOR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MESH_ADDR\" INTEGER NOT NULL ," + // 1: meshAddr
                "\"NAME\" TEXT," + // 2: name
                "\"OPEN\" INTEGER NOT NULL ," + // 3: open
                "\"MAC_ADDR\" TEXT," + // 4: macAddr
                "\"MESH_UUID\" INTEGER NOT NULL ," + // 5: meshUUID
                "\"PRODUCT_UUID\" INTEGER NOT NULL ," + // 6: productUUID
                "\"BELONG_GROUP_ID\" INTEGER," + // 7: belongGroupId
                "\"INDEX\" INTEGER NOT NULL ," + // 8: index
                "\"COLOR\" INTEGER NOT NULL ," + // 9: color
                "\"STATUS\" INTEGER NOT NULL );"); // 10: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_CONNECTOR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbConnector entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMeshAddr());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getOpen() ? 1L: 0L);
 
        String macAddr = entity.getMacAddr();
        if (macAddr != null) {
            stmt.bindString(5, macAddr);
        }
        stmt.bindLong(6, entity.getMeshUUID());
        stmt.bindLong(7, entity.getProductUUID());
 
        Long belongGroupId = entity.getBelongGroupId();
        if (belongGroupId != null) {
            stmt.bindLong(8, belongGroupId);
        }
        stmt.bindLong(9, entity.getIndex());
        stmt.bindLong(10, entity.getColor());
        stmt.bindLong(11, entity.getStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbConnector entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMeshAddr());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getOpen() ? 1L: 0L);
 
        String macAddr = entity.getMacAddr();
        if (macAddr != null) {
            stmt.bindString(5, macAddr);
        }
        stmt.bindLong(6, entity.getMeshUUID());
        stmt.bindLong(7, entity.getProductUUID());
 
        Long belongGroupId = entity.getBelongGroupId();
        if (belongGroupId != null) {
            stmt.bindLong(8, belongGroupId);
        }
        stmt.bindLong(9, entity.getIndex());
        stmt.bindLong(10, entity.getColor());
        stmt.bindLong(11, entity.getStatus());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbConnector readEntity(Cursor cursor, int offset) {
        DbConnector entity = new DbConnector( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // meshAddr
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.getShort(offset + 3) != 0, // open
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // macAddr
            cursor.getInt(offset + 5), // meshUUID
            cursor.getInt(offset + 6), // productUUID
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // belongGroupId
            cursor.getInt(offset + 8), // index
            cursor.getInt(offset + 9), // color
            cursor.getInt(offset + 10) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbConnector entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMeshAddr(cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOpen(cursor.getShort(offset + 3) != 0);
        entity.setMacAddr(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMeshUUID(cursor.getInt(offset + 5));
        entity.setProductUUID(cursor.getInt(offset + 6));
        entity.setBelongGroupId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setIndex(cursor.getInt(offset + 8));
        entity.setColor(cursor.getInt(offset + 9));
        entity.setStatus(cursor.getInt(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbConnector entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbConnector entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbConnector entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
