package com.dadoutek.uled.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dadoutek.uled.gateway.bean.DbGateway;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_GATEWAY".
*/
public class DbGatewayDao extends AbstractDao<DbGateway, Long> {

    public static final String TABLENAME = "DB_GATEWAY";

    /**
     * Properties of entity DbGateway.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MeshAddr = new Property(1, int.class, "meshAddr", false, "MESH_ADDR");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property MacAddr = new Property(3, String.class, "macAddr", false, "MAC_ADDR");
        public final static Property SixByteMacAddr = new Property(4, String.class, "sixByteMacAddr", false, "SIX_BYTE_MAC_ADDR");
        public final static Property Type = new Property(5, int.class, "type", false, "TYPE");
        public final static Property ProductUUID = new Property(6, int.class, "productUUID", false, "PRODUCT_UUID");
        public final static Property Version = new Property(7, String.class, "version", false, "VERSION");
        public final static Property BelongRegionId = new Property(8, int.class, "belongRegionId", false, "BELONG_REGION_ID");
        public final static Property Pos = new Property(9, int.class, "pos", false, "POS");
        public final static Property Uid = new Property(10, int.class, "uid", false, "UID");
        public final static Property Tags = new Property(11, String.class, "tags", false, "TAGS");
        public final static Property TimePeriodTags = new Property(12, String.class, "timePeriodTags", false, "TIME_PERIOD_TAGS");
        public final static Property AddTag = new Property(13, int.class, "addTag", false, "ADD_TAG");
        public final static Property State = new Property(14, int.class, "state", false, "STATE");
        public final static Property OpenTag = new Property(15, int.class, "openTag", false, "OPEN_TAG");
        public final static Property IsMostNew = new Property(16, boolean.class, "isMostNew", false, "IS_MOST_NEW");
        public final static Property IsGetVersion = new Property(17, boolean.class, "isGetVersion", false, "IS_GET_VERSION");
        public final static Property Rssi = new Property(18, int.class, "rssi", false, "RSSI");
        public final static Property IsSupportOta = new Property(19, boolean.class, "isSupportOta", false, "IS_SUPPORT_OTA");
    }


    public DbGatewayDao(DaoConfig config) {
        super(config);
    }
    
    public DbGatewayDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_GATEWAY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MESH_ADDR\" INTEGER NOT NULL ," + // 1: meshAddr
                "\"NAME\" TEXT," + // 2: name
                "\"MAC_ADDR\" TEXT," + // 3: macAddr
                "\"SIX_BYTE_MAC_ADDR\" TEXT," + // 4: sixByteMacAddr
                "\"TYPE\" INTEGER NOT NULL ," + // 5: type
                "\"PRODUCT_UUID\" INTEGER NOT NULL ," + // 6: productUUID
                "\"VERSION\" TEXT," + // 7: version
                "\"BELONG_REGION_ID\" INTEGER NOT NULL ," + // 8: belongRegionId
                "\"POS\" INTEGER NOT NULL ," + // 9: pos
                "\"UID\" INTEGER NOT NULL ," + // 10: uid
                "\"TAGS\" TEXT," + // 11: tags
                "\"TIME_PERIOD_TAGS\" TEXT," + // 12: timePeriodTags
                "\"ADD_TAG\" INTEGER NOT NULL ," + // 13: addTag
                "\"STATE\" INTEGER NOT NULL ," + // 14: state
                "\"OPEN_TAG\" INTEGER NOT NULL ," + // 15: openTag
                "\"IS_MOST_NEW\" INTEGER NOT NULL ," + // 16: isMostNew
                "\"IS_GET_VERSION\" INTEGER NOT NULL ," + // 17: isGetVersion
                "\"RSSI\" INTEGER NOT NULL ," + // 18: rssi
                "\"IS_SUPPORT_OTA\" INTEGER NOT NULL );"); // 19: isSupportOta
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_GATEWAY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbGateway entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMeshAddr());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String macAddr = entity.getMacAddr();
        if (macAddr != null) {
            stmt.bindString(4, macAddr);
        }
 
        String sixByteMacAddr = entity.getSixByteMacAddr();
        if (sixByteMacAddr != null) {
            stmt.bindString(5, sixByteMacAddr);
        }
        stmt.bindLong(6, entity.getType());
        stmt.bindLong(7, entity.getProductUUID());
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(8, version);
        }
        stmt.bindLong(9, entity.getBelongRegionId());
        stmt.bindLong(10, entity.getPos());
        stmt.bindLong(11, entity.getUid());
 
        String tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(12, tags);
        }
 
        String timePeriodTags = entity.getTimePeriodTags();
        if (timePeriodTags != null) {
            stmt.bindString(13, timePeriodTags);
        }
        stmt.bindLong(14, entity.getAddTag());
        stmt.bindLong(15, entity.getState());
        stmt.bindLong(16, entity.getOpenTag());
        stmt.bindLong(17, entity.getIsMostNew() ? 1L: 0L);
        stmt.bindLong(18, entity.getIsGetVersion() ? 1L: 0L);
        stmt.bindLong(19, entity.getRssi());
        stmt.bindLong(20, entity.getIsSupportOta() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbGateway entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMeshAddr());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String macAddr = entity.getMacAddr();
        if (macAddr != null) {
            stmt.bindString(4, macAddr);
        }
 
        String sixByteMacAddr = entity.getSixByteMacAddr();
        if (sixByteMacAddr != null) {
            stmt.bindString(5, sixByteMacAddr);
        }
        stmt.bindLong(6, entity.getType());
        stmt.bindLong(7, entity.getProductUUID());
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(8, version);
        }
        stmt.bindLong(9, entity.getBelongRegionId());
        stmt.bindLong(10, entity.getPos());
        stmt.bindLong(11, entity.getUid());
 
        String tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(12, tags);
        }
 
        String timePeriodTags = entity.getTimePeriodTags();
        if (timePeriodTags != null) {
            stmt.bindString(13, timePeriodTags);
        }
        stmt.bindLong(14, entity.getAddTag());
        stmt.bindLong(15, entity.getState());
        stmt.bindLong(16, entity.getOpenTag());
        stmt.bindLong(17, entity.getIsMostNew() ? 1L: 0L);
        stmt.bindLong(18, entity.getIsGetVersion() ? 1L: 0L);
        stmt.bindLong(19, entity.getRssi());
        stmt.bindLong(20, entity.getIsSupportOta() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbGateway readEntity(Cursor cursor, int offset) {
        DbGateway entity = new DbGateway( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // meshAddr
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // macAddr
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // sixByteMacAddr
            cursor.getInt(offset + 5), // type
            cursor.getInt(offset + 6), // productUUID
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // version
            cursor.getInt(offset + 8), // belongRegionId
            cursor.getInt(offset + 9), // pos
            cursor.getInt(offset + 10), // uid
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // tags
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // timePeriodTags
            cursor.getInt(offset + 13), // addTag
            cursor.getInt(offset + 14), // state
            cursor.getInt(offset + 15), // openTag
            cursor.getShort(offset + 16) != 0, // isMostNew
            cursor.getShort(offset + 17) != 0, // isGetVersion
            cursor.getInt(offset + 18), // rssi
            cursor.getShort(offset + 19) != 0 // isSupportOta
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbGateway entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMeshAddr(cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMacAddr(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSixByteMacAddr(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setType(cursor.getInt(offset + 5));
        entity.setProductUUID(cursor.getInt(offset + 6));
        entity.setVersion(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setBelongRegionId(cursor.getInt(offset + 8));
        entity.setPos(cursor.getInt(offset + 9));
        entity.setUid(cursor.getInt(offset + 10));
        entity.setTags(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTimePeriodTags(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setAddTag(cursor.getInt(offset + 13));
        entity.setState(cursor.getInt(offset + 14));
        entity.setOpenTag(cursor.getInt(offset + 15));
        entity.setIsMostNew(cursor.getShort(offset + 16) != 0);
        entity.setIsGetVersion(cursor.getShort(offset + 17) != 0);
        entity.setRssi(cursor.getInt(offset + 18));
        entity.setIsSupportOta(cursor.getShort(offset + 19) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbGateway entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbGateway entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbGateway entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
