package com.dadoutek.uled.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dadoutek.uled.gateway.bean.DbGateway;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_GATEWAY".
*/
public class DbGatewayDao extends AbstractDao<DbGateway, Long> {

    public static final String TABLENAME = "DB_GATEWAY";

    /**
     * Properties of entity DbGateway.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MeshAddr = new Property(1, int.class, "meshAddr", false, "MESH_ADDR");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property MacAddr = new Property(3, String.class, "macAddr", false, "MAC_ADDR");
        public final static Property Type = new Property(4, int.class, "type", false, "TYPE");
        public final static Property ProductUUID = new Property(5, int.class, "productUUID", false, "PRODUCT_UUID");
        public final static Property Version = new Property(6, String.class, "version", false, "VERSION");
        public final static Property BelongRegionId = new Property(7, int.class, "belongRegionId", false, "BELONG_REGION_ID");
        public final static Property Pos = new Property(8, int.class, "pos", false, "POS");
        public final static Property Uid = new Property(9, int.class, "uid", false, "UID");
        public final static Property Tags = new Property(10, String.class, "tags", false, "TAGS");
        public final static Property TimePeriodTags = new Property(11, String.class, "timePeriodTags", false, "TIME_PERIOD_TAGS");
        public final static Property AddTag = new Property(12, int.class, "addTag", false, "ADD_TAG");
        public final static Property State = new Property(13, int.class, "state", false, "STATE");
    }


    public DbGatewayDao(DaoConfig config) {
        super(config);
    }
    
    public DbGatewayDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_GATEWAY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MESH_ADDR\" INTEGER NOT NULL ," + // 1: meshAddr
                "\"NAME\" TEXT," + // 2: name
                "\"MAC_ADDR\" TEXT," + // 3: macAddr
                "\"TYPE\" INTEGER NOT NULL ," + // 4: type
                "\"PRODUCT_UUID\" INTEGER NOT NULL ," + // 5: productUUID
                "\"VERSION\" TEXT," + // 6: version
                "\"BELONG_REGION_ID\" INTEGER NOT NULL ," + // 7: belongRegionId
                "\"POS\" INTEGER NOT NULL ," + // 8: pos
                "\"UID\" INTEGER NOT NULL ," + // 9: uid
                "\"TAGS\" TEXT," + // 10: tags
                "\"TIME_PERIOD_TAGS\" TEXT," + // 11: timePeriodTags
                "\"ADD_TAG\" INTEGER NOT NULL ," + // 12: addTag
                "\"STATE\" INTEGER NOT NULL );"); // 13: state
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_GATEWAY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbGateway entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMeshAddr());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String macAddr = entity.getMacAddr();
        if (macAddr != null) {
            stmt.bindString(4, macAddr);
        }
        stmt.bindLong(5, entity.getType());
        stmt.bindLong(6, entity.getProductUUID());
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(7, version);
        }
        stmt.bindLong(8, entity.getBelongRegionId());
        stmt.bindLong(9, entity.getPos());
        stmt.bindLong(10, entity.getUid());
 
        String tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(11, tags);
        }
 
        String timePeriodTags = entity.getTimePeriodTags();
        if (timePeriodTags != null) {
            stmt.bindString(12, timePeriodTags);
        }
        stmt.bindLong(13, entity.getAddTag());
        stmt.bindLong(14, entity.getState());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbGateway entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMeshAddr());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String macAddr = entity.getMacAddr();
        if (macAddr != null) {
            stmt.bindString(4, macAddr);
        }
        stmt.bindLong(5, entity.getType());
        stmt.bindLong(6, entity.getProductUUID());
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(7, version);
        }
        stmt.bindLong(8, entity.getBelongRegionId());
        stmt.bindLong(9, entity.getPos());
        stmt.bindLong(10, entity.getUid());
 
        String tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(11, tags);
        }
 
        String timePeriodTags = entity.getTimePeriodTags();
        if (timePeriodTags != null) {
            stmt.bindString(12, timePeriodTags);
        }
        stmt.bindLong(13, entity.getAddTag());
        stmt.bindLong(14, entity.getState());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbGateway readEntity(Cursor cursor, int offset) {
        DbGateway entity = new DbGateway( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // meshAddr
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // macAddr
            cursor.getInt(offset + 4), // type
            cursor.getInt(offset + 5), // productUUID
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // version
            cursor.getInt(offset + 7), // belongRegionId
            cursor.getInt(offset + 8), // pos
            cursor.getInt(offset + 9), // uid
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // tags
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // timePeriodTags
            cursor.getInt(offset + 12), // addTag
            cursor.getInt(offset + 13) // state
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbGateway entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMeshAddr(cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMacAddr(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setType(cursor.getInt(offset + 4));
        entity.setProductUUID(cursor.getInt(offset + 5));
        entity.setVersion(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBelongRegionId(cursor.getInt(offset + 7));
        entity.setPos(cursor.getInt(offset + 8));
        entity.setUid(cursor.getInt(offset + 9));
        entity.setTags(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTimePeriodTags(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAddTag(cursor.getInt(offset + 12));
        entity.setState(cursor.getInt(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbGateway entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbGateway entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbGateway entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
