package com.dadoutek.uled.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dadoutek.uled.model.dbModel.DbGroup;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_GROUP".
*/
public class DbGroupDao extends AbstractDao<DbGroup, Long> {

    public static final String TABLENAME = "DB_GROUP";

    /**
     * Properties of entity DbGroup.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MeshAddr = new Property(1, int.class, "meshAddr", false, "MESH_ADDR");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Brightness = new Property(3, int.class, "brightness", false, "BRIGHTNESS");
        public final static Property ColorTemperature = new Property(4, int.class, "colorTemperature", false, "COLOR_TEMPERATURE");
        public final static Property BelongRegionId = new Property(5, int.class, "belongRegionId", false, "BELONG_REGION_ID");
        public final static Property DeviceType = new Property(6, Long.class, "deviceType", false, "DEVICE_TYPE");
        public final static Property Index = new Property(7, int.class, "index", false, "INDEX");
        public final static Property Color = new Property(8, int.class, "color", false, "COLOR");
        public final static Property Status = new Property(9, int.class, "status", false, "STATUS");
        public final static Property SlowUpSlowDownStatus = new Property(10, int.class, "slowUpSlowDownStatus", false, "SLOW_UP_SLOW_DOWN_STATUS");
        public final static Property SlowUpSlowDownSpeed = new Property(11, int.class, "slowUpSlowDownSpeed", false, "SLOW_UP_SLOW_DOWN_SPEED");
        public final static Property RouterName = new Property(12, String.class, "routerName", false, "ROUTER_NAME");
        public final static Property RouterId = new Property(13, String.class, "routerId", false, "ROUTER_ID");
        public final static Property IsEnableWhiteLight = new Property(14, int.class, "isEnableWhiteLight", false, "IS_ENABLE_WHITE_LIGHT");
        public final static Property IsEnableBright = new Property(15, int.class, "isEnableBright", false, "IS_ENABLE_BRIGHT");
    }


    public DbGroupDao(DaoConfig config) {
        super(config);
    }
    
    public DbGroupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_GROUP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MESH_ADDR\" INTEGER NOT NULL ," + // 1: meshAddr
                "\"NAME\" TEXT," + // 2: name
                "\"BRIGHTNESS\" INTEGER NOT NULL ," + // 3: brightness
                "\"COLOR_TEMPERATURE\" INTEGER NOT NULL ," + // 4: colorTemperature
                "\"BELONG_REGION_ID\" INTEGER NOT NULL ," + // 5: belongRegionId
                "\"DEVICE_TYPE\" INTEGER," + // 6: deviceType
                "\"INDEX\" INTEGER NOT NULL ," + // 7: index
                "\"COLOR\" INTEGER NOT NULL ," + // 8: color
                "\"STATUS\" INTEGER NOT NULL ," + // 9: status
                "\"SLOW_UP_SLOW_DOWN_STATUS\" INTEGER NOT NULL ," + // 10: slowUpSlowDownStatus
                "\"SLOW_UP_SLOW_DOWN_SPEED\" INTEGER NOT NULL ," + // 11: slowUpSlowDownSpeed
                "\"ROUTER_NAME\" TEXT," + // 12: routerName
                "\"ROUTER_ID\" TEXT," + // 13: routerId
                "\"IS_ENABLE_WHITE_LIGHT\" INTEGER NOT NULL ," + // 14: isEnableWhiteLight
                "\"IS_ENABLE_BRIGHT\" INTEGER NOT NULL );"); // 15: isEnableBright
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_GROUP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbGroup entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMeshAddr());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getBrightness());
        stmt.bindLong(5, entity.getColorTemperature());
        stmt.bindLong(6, entity.getBelongRegionId());
 
        Long deviceType = entity.getDeviceType();
        if (deviceType != null) {
            stmt.bindLong(7, deviceType);
        }
        stmt.bindLong(8, entity.getIndex());
        stmt.bindLong(9, entity.getColor());
        stmt.bindLong(10, entity.getStatus());
        stmt.bindLong(11, entity.getSlowUpSlowDownStatus());
        stmt.bindLong(12, entity.getSlowUpSlowDownSpeed());
 
        String routerName = entity.getRouterName();
        if (routerName != null) {
            stmt.bindString(13, routerName);
        }
 
        String routerId = entity.getRouterId();
        if (routerId != null) {
            stmt.bindString(14, routerId);
        }
        stmt.bindLong(15, entity.getIsEnableWhiteLight());
        stmt.bindLong(16, entity.getIsEnableBright());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbGroup entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMeshAddr());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getBrightness());
        stmt.bindLong(5, entity.getColorTemperature());
        stmt.bindLong(6, entity.getBelongRegionId());
 
        Long deviceType = entity.getDeviceType();
        if (deviceType != null) {
            stmt.bindLong(7, deviceType);
        }
        stmt.bindLong(8, entity.getIndex());
        stmt.bindLong(9, entity.getColor());
        stmt.bindLong(10, entity.getStatus());
        stmt.bindLong(11, entity.getSlowUpSlowDownStatus());
        stmt.bindLong(12, entity.getSlowUpSlowDownSpeed());
 
        String routerName = entity.getRouterName();
        if (routerName != null) {
            stmt.bindString(13, routerName);
        }
 
        String routerId = entity.getRouterId();
        if (routerId != null) {
            stmt.bindString(14, routerId);
        }
        stmt.bindLong(15, entity.getIsEnableWhiteLight());
        stmt.bindLong(16, entity.getIsEnableBright());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbGroup readEntity(Cursor cursor, int offset) {
        DbGroup entity = new DbGroup( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // meshAddr
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.getInt(offset + 3), // brightness
            cursor.getInt(offset + 4), // colorTemperature
            cursor.getInt(offset + 5), // belongRegionId
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // deviceType
            cursor.getInt(offset + 7), // index
            cursor.getInt(offset + 8), // color
            cursor.getInt(offset + 9), // status
            cursor.getInt(offset + 10), // slowUpSlowDownStatus
            cursor.getInt(offset + 11), // slowUpSlowDownSpeed
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // routerName
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // routerId
            cursor.getInt(offset + 14), // isEnableWhiteLight
            cursor.getInt(offset + 15) // isEnableBright
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbGroup entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMeshAddr(cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBrightness(cursor.getInt(offset + 3));
        entity.setColorTemperature(cursor.getInt(offset + 4));
        entity.setBelongRegionId(cursor.getInt(offset + 5));
        entity.setDeviceType(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setIndex(cursor.getInt(offset + 7));
        entity.setColor(cursor.getInt(offset + 8));
        entity.setStatus(cursor.getInt(offset + 9));
        entity.setSlowUpSlowDownStatus(cursor.getInt(offset + 10));
        entity.setSlowUpSlowDownSpeed(cursor.getInt(offset + 11));
        entity.setRouterName(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setRouterId(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setIsEnableWhiteLight(cursor.getInt(offset + 14));
        entity.setIsEnableBright(cursor.getInt(offset + 15));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbGroup entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbGroup entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbGroup entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
