package com.dadoutek.uled.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dadoutek.uled.model.DbModel.DbLight;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_LIGHT".
*/
public class DbLightDao extends AbstractDao<DbLight, Long> {

    public static final String TABLENAME = "DB_LIGHT";

    /**
     * Properties of entity DbLight.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MeshAddr = new Property(1, int.class, "meshAddr", false, "MESH_ADDR");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Brightness = new Property(3, int.class, "brightness", false, "BRIGHTNESS");
        public final static Property ColorTemperature = new Property(4, int.class, "colorTemperature", false, "COLOR_TEMPERATURE");
        public final static Property MacAddr = new Property(5, String.class, "macAddr", false, "MAC_ADDR");
        public final static Property MeshUUID = new Property(6, int.class, "meshUUID", false, "MESH_UUID");
        public final static Property ProductUUID = new Property(7, int.class, "productUUID", false, "PRODUCT_UUID");
        public final static Property BelongGroupId = new Property(8, Long.class, "belongGroupId", false, "BELONG_GROUP_ID");
        public final static Property Index = new Property(9, int.class, "index", false, "INDEX");
        public final static Property Color = new Property(10, int.class, "color", false, "COLOR");
        public final static Property Status = new Property(11, int.class, "status", false, "STATUS");
    }


    public DbLightDao(DaoConfig config) {
        super(config);
    }
    
    public DbLightDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_LIGHT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MESH_ADDR\" INTEGER NOT NULL ," + // 1: meshAddr
                "\"NAME\" TEXT," + // 2: name
                "\"BRIGHTNESS\" INTEGER NOT NULL ," + // 3: brightness
                "\"COLOR_TEMPERATURE\" INTEGER NOT NULL ," + // 4: colorTemperature
                "\"MAC_ADDR\" TEXT," + // 5: macAddr
                "\"MESH_UUID\" INTEGER NOT NULL ," + // 6: meshUUID
                "\"PRODUCT_UUID\" INTEGER NOT NULL ," + // 7: productUUID
                "\"BELONG_GROUP_ID\" INTEGER," + // 8: belongGroupId
                "\"INDEX\" INTEGER NOT NULL ," + // 9: index
                "\"COLOR\" INTEGER NOT NULL ," + // 10: color
                "\"STATUS\" INTEGER NOT NULL );"); // 11: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_LIGHT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbLight entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMeshAddr());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getBrightness());
        stmt.bindLong(5, entity.getColorTemperature());
 
        String macAddr = entity.getMacAddr();
        if (macAddr != null) {
            stmt.bindString(6, macAddr);
        }
        stmt.bindLong(7, entity.getMeshUUID());
        stmt.bindLong(8, entity.getProductUUID());
 
        Long belongGroupId = entity.getBelongGroupId();
        if (belongGroupId != null) {
            stmt.bindLong(9, belongGroupId);
        }
        stmt.bindLong(10, entity.getIndex());
        stmt.bindLong(11, entity.getColor());
        stmt.bindLong(12, entity.getStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbLight entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMeshAddr());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getBrightness());
        stmt.bindLong(5, entity.getColorTemperature());
 
        String macAddr = entity.getMacAddr();
        if (macAddr != null) {
            stmt.bindString(6, macAddr);
        }
        stmt.bindLong(7, entity.getMeshUUID());
        stmt.bindLong(8, entity.getProductUUID());
 
        Long belongGroupId = entity.getBelongGroupId();
        if (belongGroupId != null) {
            stmt.bindLong(9, belongGroupId);
        }
        stmt.bindLong(10, entity.getIndex());
        stmt.bindLong(11, entity.getColor());
        stmt.bindLong(12, entity.getStatus());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbLight readEntity(Cursor cursor, int offset) {
        DbLight entity = new DbLight( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // meshAddr
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.getInt(offset + 3), // brightness
            cursor.getInt(offset + 4), // colorTemperature
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // macAddr
            cursor.getInt(offset + 6), // meshUUID
            cursor.getInt(offset + 7), // productUUID
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // belongGroupId
            cursor.getInt(offset + 9), // index
            cursor.getInt(offset + 10), // color
            cursor.getInt(offset + 11) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbLight entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMeshAddr(cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBrightness(cursor.getInt(offset + 3));
        entity.setColorTemperature(cursor.getInt(offset + 4));
        entity.setMacAddr(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMeshUUID(cursor.getInt(offset + 6));
        entity.setProductUUID(cursor.getInt(offset + 7));
        entity.setBelongGroupId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setIndex(cursor.getInt(offset + 9));
        entity.setColor(cursor.getInt(offset + 10));
        entity.setStatus(cursor.getInt(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbLight entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbLight entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbLight entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
