package com.dadoutek.uled.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dadoutek.uled.model.DbModel.DbScene;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_SCENE".
*/
public class DbSceneDao extends AbstractDao<DbScene, Long> {

    public static final String TABLENAME = "DB_SCENE";

    /**
     * Properties of entity DbScene.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property BelongRegionId = new Property(2, Long.class, "belongRegionId", false, "BELONG_REGION_ID");
        public final static Property Index = new Property(3, int.class, "index", false, "INDEX");
        public final static Property Times = new Property(4, String.class, "times", false, "TIMES");
    }

    private DaoSession daoSession;


    public DbSceneDao(DaoConfig config) {
        super(config);
    }
    
    public DbSceneDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_SCENE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"BELONG_REGION_ID\" INTEGER NOT NULL ," + // 2: belongRegionId
                "\"INDEX\" INTEGER NOT NULL ," + // 3: index
                "\"TIMES\" TEXT);"); // 4: times
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_SCENE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbScene entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getBelongRegionId());
        stmt.bindLong(4, entity.getIndex());
 
        String times = entity.getTimes();
        if (times != null) {
            stmt.bindString(5, times);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbScene entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getBelongRegionId());
        stmt.bindLong(4, entity.getIndex());
 
        String times = entity.getTimes();
        if (times != null) {
            stmt.bindString(5, times);
        }
    }

    @Override
    protected final void attachEntity(DbScene entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbScene readEntity(Cursor cursor, int offset) {
        DbScene entity = new DbScene( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.getLong(offset + 2), // belongRegionId
            cursor.getInt(offset + 3), // index
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // times
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbScene entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBelongRegionId(cursor.getLong(offset + 2));
        entity.setIndex(cursor.getInt(offset + 3));
        entity.setTimes(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbScene entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbScene entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbScene entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
